---
deployment:
  tasks:
    - export DEPLOYPATH=/home/simt1698/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R application/controllers $DEPLOYPATH
    - /bin/cp -R application/models $DEPLOYPATH
    - /bin/cp -R application/views $DEPLOYPATH
    - /bin/cp -R application/migrations $DEPLOYPATH    
    - /bin/cp -R application/helpers $DEPLOYPATH
    - /bin/cp -R application/config/migration.php $DEPLOYPATH